#!/bin/bash

./bin/rt --out_file=out.ppm \
        --image_width=750 \
        --aspect_ratio=1/1 \
        --vfov=60 \
        --samples_per_pixel=20 \
        --use_path_tracer \
        --use_light_sampling  \
        --background_image=./assets/pano2.jpg \
        --use_importance_sampling \
        --max_depth=5